# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4e1fbe99fba5bf48f094895616d6f622"
name = "photo gallery app "
handle = "photo-gallery-app-1"
application_url = "https://marco-fonts-childrens-uses.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers, unauthenticated_read_customers,unauthenticated_write_customers,read_themes,write_themes"

[auth]
redirect_urls = ["https://marco-fonts-childrens-uses.trycloudflare.com/auth/callback", "https://marco-fonts-childrens-uses.trycloudflare.com/auth/shopify/callback", "https://marco-fonts-childrens-uses.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[[extensions]]
type = "theme_app_extension"
name = "Gallery Blocks"
handle = "gallery-blocks"
description = "Adds gallery functionality to your store"
[[extensions.block]]
name = "content_gallery"
type = "dynamic"
template = "blocks/content-gallery.liquid"
[[extensions.block]]
name = "app_gallery"
type = "dynamic"
template = "blocks/app-gallery.liquid"
